FROM node:slim
WORKDIR /app/api
ENV DB_USER="sa"
ENV DB_PWD="SQLstrongPass123"
ENV DB_NAME=Boardgame
ENV PRIVATE_KEY=sadjlkwqjoioqieoiwasidjskaljlkioghoiuqhoiugqgqwgqwgq
COPY package.json .
RUN npm i
COPY . .
EXPOSE 3000
CMD ["node", "./src/app.js"]
